name: Semantic Release
on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v3

      - name: Setup yarn
        run: |
          asdf plugin add yarn
          asdf install yarn

      - name: Setup Node version
        run: |
          asdf plugin add nodejs
          asdf install nodejs
          echo "node_version=$(asdf current nodejs | xargs | cut -d ' ' -f 2)" >> $GITHUB_ENV

      - name: Set nodejs as global exec
        run: |
          asdf global nodejs ${{ env.node_version }}

      - name: Cache node_modules
        id: node_modules-cache
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.OS }}-node-${{ env.node_version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.OS }}-node-${{ env.node_version }}-

      - name: Install NPM dependencies
        working-directory: ./
        run: yarn

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
